<?php
$exp_date = "MyBub3ZlbWJlciAyMDEz";
$exp_alert = "PHA+PHN0cm9uZz5URVJNIERFTU8gTElDRU5TRSBFWFBJUkVEITwvc3Ryb25nPjwvcD4gPHA+ClRPIENPTlRJTlVFIFRIRSBTSVRFIDxzdHJvbmc+TVVTVCBCRSBQQUlEIFdlYiBTaXRlIERldmVsb3BtZW50PC9zdHJvbmc+PC9wPg==";
?>